//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ats.Commons.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ats.Commons.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity has been assigned.
        /// </summary>
        public static string ActivityHasBeenAssigned {
            get {
                return ResourceManager.GetString("ActivityHasBeenAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change approved leave ticket.
        /// </summary>
        public static string CantChangeApprovedLeaveTicket {
            get {
                return ResourceManager.GetString("CantChangeApprovedLeaveTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change approved timelog.
        /// </summary>
        public static string CantChangeApprovedTimelog {
            get {
                return ResourceManager.GetString("CantChangeApprovedTimelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete approved timelog.
        /// </summary>
        public static string CantDeleteApprovedTimelog {
            get {
                return ResourceManager.GetString("CantDeleteApprovedTimelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code has been used.
        /// </summary>
        public static string CodeHasBeenUsed {
            get {
                return ResourceManager.GetString("CodeHasBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPW {
            get {
                return ResourceManager.GetString("ConfirmNewPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurPW {
            get {
                return ResourceManager.GetString("CurPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time cannot overlap.
        /// </summary>
        public static string DatesCannotOverlap {
            get {
                return ResourceManager.GetString("DatesCannotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device user ID has been used.
        /// </summary>
        public static string DeviceUserIDHasBeenUsed {
            get {
                return ResourceManager.GetString("DeviceUserIDHasBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email used.
        /// </summary>
        public static string EmailUsed {
            get {
                return ResourceManager.GetString("EmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ErrorConfirmPW {
            get {
                return ResourceManager.GetString("ErrorConfirmPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave ticket has been expired. Can not withdraw.
        /// </summary>
        public static string LeaveTicketExpiredCantWithdraw {
            get {
                return ResourceManager.GetString("LeaveTicketExpiredCantWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave type was created.
        /// </summary>
        public static string LeaveTypeCreated {
            get {
                return ResourceManager.GetString("LeaveTypeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is null.
        /// </summary>
        public static string ModelIsNull {
            get {
                return ResourceManager.GetString("ModelIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model not found.
        /// </summary>
        public static string ModelNotFound {
            get {
                return ResourceManager.GetString("ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPW {
            get {
                return ResourceManager.GetString("NewPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission to approve this timelog.
        /// </summary>
        public static string NoPermissionToApproveTimelog {
            get {
                return ResourceManager.GetString("NoPermissionToApproveTimelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission to delete leave.
        /// </summary>
        public static string NoPermissionToDeleteLeave {
            get {
                return ResourceManager.GetString("NoPermissionToDeleteLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been assigned.
        /// </summary>
        public static string RoleHasBeenAssigned {
            get {
                return ResourceManager.GetString("RoleHasBeenAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time overlaps with work shift of the last day.
        /// </summary>
        public static string TimeOverlapLastDay {
            get {
                return ResourceManager.GetString("TimeOverlapLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time overlaps with work shift of the next day.
        /// </summary>
        public static string TimeOverlapNextDay {
            get {
                return ResourceManager.GetString("TimeOverlapNextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been assigned.
        /// </summary>
        public static string UserHasBeenAssigned {
            get {
                return ResourceManager.GetString("UserHasBeenAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usename has been used.
        /// </summary>
        public static string UserNameUsed {
            get {
                return ResourceManager.GetString("UserNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
